// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from 'react';

const Test = function (Props) {
  return React.createElement('h1', {
    className: 'text-4xl md:text-8xl bg-clip-text text-transparent bg-gradient-to-r from-red-400 to-blue-700 font-extrabold md:mb-6 p-2',
  }, "Let's build something cool!");
};

const make = Test;

export {
  make,

};
/* react Not a pure module */
